export const DECREMENT_MESSAGE = 'DECREMENT_MESSAGE';
export const INCREMENT_MESSAGE = 'INCREMENT_MESSAGE';
export const REQUEST_MESSAGE = 'REQUEST_MESSAGE';
export const SUCCESS_MESSAGE = 'SUCCESS_MESSAGE';
export const FAILURE_MESSAGE = 'FAILURE_MESSAGE';
